import "package:flutter/material.dart";

class CustomSliverAppBar extends SliverAppBar {
  CustomSliverAppBar({
    Key key,
    leading,
    automaticallyImplyLeading = true,
    pinned = false,
    floating = false,
    title,
    actions,
    bottom,
    elevation = 0.0,
    borderRadius,
    shape,
    backgroundColor,
    brightness: Brightness.dark,
    iconTheme,
    actionsIconTheme,
    textTheme,
    primary = true,
    centerTitle = true,
    titleSpacing = NavigationToolbar.kMiddleSpacing,
    flexibleSpace,
  }) : super(
          key: key,
          leading: leading,
          automaticallyImplyLeading: automaticallyImplyLeading,
          pinned: pinned,
          floating: floating,
          title: title,
          actions: actions,
          shape: shape,
          bottom: bottom,
          elevation: elevation,
          backgroundColor: backgroundColor,
          brightness: brightness,
          iconTheme: iconTheme,
          actionsIconTheme: actionsIconTheme,
          textTheme: textTheme,
          primary: primary,
          centerTitle: centerTitle,
          flexibleSpace: flexibleSpace,
          titleSpacing: titleSpacing,
        );
}
